### ISSUE TITLE
php artisan make:module:migration fails due to views not found

### ISSUE THREAD

**Issue by salhdev** [sroutier/l51esk-modules#1]
Hi, 
This is an issue common to several l51ESK commands (like queue workers) and is due to the fact that the Theme does not get initialized so therefore its path can not be found !

I have resolved this issue by adding   \Theme::init('default'); in each _construct of the concerned command !

Regards,
Salh

**Comment by sroutier** [comment]
Hello @sraffali, Thanks for taking the time to file a report, I appreciate it.

I tried to run `make:module:migration` on both an enabled or disabled module and did not have a problem. I also enabled and disabled the module in question using the artisan commands `module:enable` and `module:enable`.

I then tried the command `queue:failed` and did get an error that it could not locate the `...View [emails.html.lern_notification]...`. Which is, as you correctly identified, caused by the Theme engine not being initialized, when the LERN engine is triggered by an exception and cannot locate the email template stored under a theme directory.

I was able to fix this issue by adding the expected email template in the default location that the FileViewFinder will be looking into before the Theme engine is initialized, ie: `resources/views/emails/html/`. 

This does cause a little duplication of the email template file but it as 2 advantages, first it resolves this issue not only for the commands where we can add the required `\Theme::init('default');`, as you have done it, but also for all other Artisan command to which we cannot easily modify the code. Additionally this duplication shows how a template can both degrade to its base when not available in the theme, or the theme not exist yet, and also how to override a base template within a theme to provide a different rendering.

I just committed the fix to the [sroutier/laravel-5.1-enterprise-starter-kit](https://github.com/sroutier/laravel-5.1-enterprise-starter-kit), could you try it and let me know if it resolves your issue?

Thank you.
/s

**Comment by salhdev** [comment]
Hi Sebastien, thanks for your reactivity !
Yes indeed It has resolved the issue, I had previously moved the blade template to the standard location to see if it was an issue with the theme path or not, that's how I came up with the idea of initialising it (but was not a long term solution).
I would agree with you on the fact that all system templates should reside on the standard directories as they are common to all, and themes should only be used a an override for changes that are specific to that theme. That way nothing breaks when a theme is not present.

Thanks again,
Salh

**Comment by sroutier** [comment]
👍 
Thanks for the help. One bug down.
/s
